---
- name: "Load variables based on OS family"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "main.yml"

- name: "Choose platform based task"
  include_tasks: "{{ lookup('first_found', tasks)}}"
  vars:
    tasks:
      - '{{ ansible_distribution }}.yml'
      - '{{ ansible_os_family }}.yml'
      - '{{ ansible_facts.system }}.yml'
      - 'unsupported.yml'

- name: "Install requirements"
  package:
    name: "{{ required_packages }}"
    state: present
  register: status
  retries: 10
  delay: 2
  until: status is success
  become: True
  when: (required_packages | length > 0)
